#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Dynamic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using A2v10.Web.Mvc;
    using Microsoft.AspNet.Identity;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public partial class _Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(" />\r\n    <title>A2:Web</title>\r\n    <link");

WriteLiteral(" href=\"/css/site.min.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n</head>\r\n<body>\r\n    <div");

WriteLiteral(" id=\"app\"");

WriteLiteral(" class=\"shell\"");

WriteLiteral(">\r\n        <header");

WriteLiteral(" class=\"header\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"h-block\"");

WriteLiteral(">\r\n                <!--<i class=\"ico-user\"></i>-->\r\n                <a");

WriteLiteral(" class=\"app-title\"");

WriteLiteral(" href=\'/\'");

WriteLiteral(" v-on:click.prevent=\"root\"");

WriteLiteral(" v-text=\"title\"");

WriteLiteral("></a>\r\n                <span");

WriteLiteral(" class=\"app-subtitle\"");

WriteLiteral(" v-text=\"subtitle\"");

WriteLiteral("></span>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"aligner\"");

WriteLiteral("></div>\r\n        </header>\r\n        <div");

WriteLiteral(" class=\"main-view\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"content-view full-view\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 22 "..\..\Views\Shared\_Layout.cshtml"
           Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <footer");

WriteLiteral(" class=\"footer\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" :class=\"{spinner: true, active:processing}\"");

WriteLiteral("></div>\r\n            version: <span");

WriteLiteral(" v-text=\"version\"");

WriteLiteral("></span>\r\n        </footer>\r\n    </div>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/scripts/vue.min.js?v=2.4.2\"");

WriteLiteral("></script>\r\n");

WriteLiteral("    ");

            
            #line 31 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("Scripts", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
