#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Dynamic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using A2v10.Web.Mvc;
    using Microsoft.AspNet.Identity;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public partial class _Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n");

            
            #line 2 "..\..\Views\Shared\_Layout.cshtml"
  
	String currentBuild = "1234";

            
            #line default
            #line hidden
WriteLiteral("\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(">\r\n    <title>");

            
            #line 9 "..\..\Views\Shared\_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(" - A2v10</title>\r\n\t<link");

WriteLiteral(" href=\"/css/font-awesome.min.css?v=4.7.0\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\t<link");

WriteLiteral(" href=\"/css/site.min.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral("/>\r\n</head>\r\n<body>\r\n\t<div");

WriteLiteral(" id=\"app\"");

WriteLiteral(">\r\n\t\t<div");

WriteLiteral(" class=\"navbar navbar-inverse navbar-fixed-top\"");

WriteLiteral(">\r\n\t\t\t<div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n\t\t\t\t<i");

WriteLiteral(" class=\"fa fa-user\"");

WriteLiteral("></i>\r\n\t\t\t\t<div");

WriteLiteral(" class=\"navbar-collapse collapse\"");

WriteLiteral(">\r\n\t\t\t\t\t<ul");

WriteLiteral(" class=\"nav navbar-nav\"");

WriteLiteral(">\r\n\t\t\t\t\t\t<li>");

            
            #line 20 "..\..\Views\Shared\_Layout.cshtml"
                       Write(Html.ActionLink("Home", "Index", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n\t\t\t\t\t\t<li>");

            
            #line 21 "..\..\Views\Shared\_Layout.cshtml"
                       Write(Html.ActionLink("About", "About", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n\t\t\t\t\t\t<li>");

            
            #line 22 "..\..\Views\Shared\_Layout.cshtml"
                       Write(Html.ActionLink("Contact", "Contact", "Home"));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n\t\t\t\t\t</ul>\r\n");

WriteLiteral("\t\t\t\t\t");

            
            #line 24 "..\..\Views\Shared\_Layout.cshtml"
               Write(Html.Partial("_LoginPartial"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t</div>\r\n\t\t\t</div>\r\n\t\t</div>\r\n\t\t<div");

WriteLiteral(" class=\"container body-content\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t");

            
            #line 29 "..\..\Views\Shared\_Layout.cshtml"
       Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t<hr />\r\n\t\t</div>\r\n\t\t<footer");

WriteLiteral(" class=\"footer\"");

WriteLiteral(">\r\n\t\t\t<p>&copy; ");

            
            #line 33 "..\..\Views\Shared\_Layout.cshtml"
                 Write(DateTime.Now.Year);

            
            #line default
            #line hidden
WriteLiteral("  ");

            
            #line 33 "..\..\Views\Shared\_Layout.cshtml"
                                     Write(A2v10.Web.Mvc.Configuration.AppInfo.MainAssembly.Version);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n\t\t</footer>\r\n\t</div>\r\n\t<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"/Scripts/vue.min.js?v=2.3.4\"");

WriteLiteral("></script>\r\n\t<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 1164), Tuple.Create("\"", 1217)
            
            #line 37 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1170), Tuple.Create<System.Object, System.Int32>(Html.Raw("/Scripts/main.js?v=" + currentBuild)
            
            #line default
            #line hidden
, 1170), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    ");

            
            #line 38 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
