#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Dynamic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\StiReport.cshtml"
    using A2v10.Reports;
    
    #line default
    #line hidden
    using A2v10.Web.Mvc;
    using Microsoft.AspNet.Identity;
    
    #line 2 "..\..\Views\Shared\StiReport.cshtml"
    using Stimulsoft.Report.Mvc;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Shared\StiReport.cshtml"
    using Stimulsoft.Report.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/StiReport.cshtml")]
    public partial class _Views_Shared_StiReport_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_StiReport_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Shared\StiReport.cshtml"
  
	Layout = null;
	String locale = String.IsNullOrEmpty(ViewBag.Lang) ? "uk" : ViewBag.Lang;
	String localeFile = $"~/Localization/{locale}.xml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<!DOCTYPE html>\r\n<html");

WriteAttribute("lang", Tuple.Create(" lang=\"", 261), Tuple.Create("\"", 281)
            
            #line 10 "..\..\Views\Shared\StiReport.cshtml"
, Tuple.Create(Tuple.Create("", 268), Tuple.Create<System.Object, System.Int32>(ViewBag.Lang
            
            #line default
            #line hidden
, 268), false)
);

WriteLiteral(">\r\n<head>\r\n\t<meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n\t<meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(" />\r\n\t<title>");

            
            #line 14 "..\..\Views\Shared\StiReport.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n\t<style>\r\n\t\tbody {\r\n\t\t\tbackground-color: #e3e3e3;\r\n\t\t}\r\n\t</style>\r\n</he" +
"ad>\r\n<body");

WriteLiteral(" scroll=\"none\"");

WriteLiteral(">\r\n");

WriteLiteral("\t");

            
            #line 22 "..\..\Views\Shared\StiReport.cshtml"
Write(Html.Stimulsoft().StiMvcViewer("A2v10StiMvcViewer",
				new StiMvcViewerOptions()
				{
					Theme = StiViewerTheme.Office2013LightGrayBlue,
					Localization = localeFile,
					Server = new StiMvcViewerOptions.ServerOptions()
					{
						Controller = "StiReport",
						RequestTimeout = 300,
						UseRelativeUrls = true
					},
					Actions = new StiMvcViewerOptions.ActionOptions()
					{
						GetReport = "GetReport",
						ViewerEvent = "ViewerEvent",
						PrintReport = "PrintReport",
						ExportReport = "ExportReport",
						Interaction = "Interaction",
					},
					Appearance = new StiMvcViewerOptions.AppearanceOptions()
					{
						BackgroundColor = System.Drawing.Color.FromArgb(0x00e3e3e3),
						ShowTooltips = false,
						ScrollbarsMode = true,
						FullScreenMode = true,
					},
					Toolbar = new StiMvcViewerOptions.ToolbarOptions()
					{
						MenuAnimation = false,
						ShowFullScreenButton = false,
						ShowMenuMode = StiShowMenuMode.Click,
						FontFamily = "Segoe UI,Tahoma,Arial,Verdana,Sans-Serif",
						FontColor = System.Drawing.Color.FromArgb(0x00333333),
						ShowBookmarksButton = false,
						ShowParametersButton = true,
						ShowSendEmailButton = false,
					},
					Exports = new StiMvcViewerOptions.ExportOptions()
					{
						DefaultSettings = StiReportExtensions.GetExportSettings()
					}
				}
			));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
