//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A2v10.Request.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("A2v10.Request.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;page absolute page-grid&quot; id=&quot;$(PageGuid)&quot;&gt;
        ///	&lt;a2-document-title page-title=&quot;@[About]&quot;&gt;&lt;/a2-document-title&gt;
        ///	&lt;div class=&quot;toolbar page-toolbar&quot;&gt;
        ///		&lt;button class=&quot;btn btn-tb&quot; @click.prevent=&quot;$requery&quot;&gt;&lt;i class=&quot;ico ico-reload&quot;&gt;&lt;/i&gt; @[Refresh]&lt;/button&gt;
        ///		&lt;div class=&quot;aligner&quot;&gt;&lt;/div&gt;
        ///		&lt;button class=&quot;btn btn-tb&quot; @click.prevent=&quot;$close&quot;&gt;&lt;i class=&quot;ico ico-close&quot;&gt;&lt;/i&gt; @[Close]&lt;/button&gt;
        ///	&lt;/div&gt;
        ///	&lt;div class=&quot;page-content&quot;&gt;
        ///		&lt;div class=&quot;grid app-page&quot;&gt;
        ///			&lt;h3 class=&quot;a2-header&quot; v-text=&quot;appData.title [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright © 2015-2018 Alex Kukhtin. All rights reserved.
        ///
        ///(function () {
        ///
        ///	&apos;use strict&apos;;
        ///
        ///	const eventBus = require(&apos;std:eventBus&apos;);
        ///
        ///	const store = component(&apos;std:store&apos;);
        ///	const documentTitle = component(&quot;std:doctitle&quot;);
        ///
        ///
        ///	const vm = new Vue({
        ///		el: &quot;#$(PageGuid)&quot;,
        ///		store: store,
        ///		data: {
        ///			appData: $(AppData)
        ///		},
        ///		components: {
        ///			&apos;a2-document-title&apos;: documentTitle
        ///		},
        ///		computed: {
        ///			locale() {
        ///				return window.$$locale;
        ///			}
        ///		},
        ///		methods: {
        ///			$close() {
        ///				th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string aboutScript {
            get {
                return ResourceManager.GetString("aboutScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright © 2015-2018 Alex Kukhtin. All rights reserved.
        ///
        ///(function () {
        ///
        ///	$(Utils)
        ///	$(Locale)
        ///
        ///	const vm = new Vue({
        ///		el: &quot;#app&quot;,
        ///		components: {
        ///			&quot;a2-document-title&quot;: {
        ///				props: {
        ///					pageTitle: String
        ///				},
        ///				created() {
        ///					if (this.pageTitle)
        ///						document.title = this.pageTitle;
        ///				}
        ///			}
        ///		},
        ///		data: {
        ///			info: $(PageData),
        ///			processing: false,
        ///			appLinks: $(AppLinks)
        ///		},
        ///		computed: {
        ///			locale() {
        ///				return window.$$locale;
        ///			}
        ///		},
        ///		methods: {
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string appLinkScript {
            get {
                return ResourceManager.GetString("appLinkScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;page absolute page-grid&quot; id=&quot;$(PageGuid)&quot;&gt;
        ///	&lt;div class=&quot;toolbar page-toolbar&quot;&gt;
        ///		&lt;button class=&quot;btn btn-tb&quot; @click.prevent=&quot;$requery&quot;&gt;&lt;i class=&quot;ico ico-reload&quot;&gt;&lt;/i&gt; @[Refresh]&lt;/button&gt;
        ///		&lt;div class=&quot;aligner&quot;&gt;&lt;/div&gt;
        ///		&lt;button class=&quot;btn btn-tb&quot; @click.prevent=&quot;$close&quot;&gt;&lt;i class=&quot;ico ico-close&quot;&gt;&lt;/i&gt; @[Close]&lt;/button&gt;
        ///	&lt;/div&gt;
        ///	&lt;div class=&quot;page-content app-page&quot;&gt;
        ///		$(AppPageContent)
        ///	&lt;/div&gt;
        ///&lt;/div&gt;
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        ///	$(AppPageScript)
        ///&lt;/script&gt;.
        /// </summary>
        internal static string appPage {
            get {
                return ResourceManager.GetString("appPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright © 2015-2018 Alex Kukhtin. All rights reserved.
        ///
        ///&apos;use strict&apos;;
        ///
        ///(function () {
        ///
        ///
        ///	const eventBus = require(&apos;std:eventBus&apos;);
        ///
        ///	const store = component(&apos;std:store&apos;);
        ///	const documentTitle = component(&quot;std:doctitle&quot;);
        ///
        ///
        ///	const vm = new Vue({
        ///		el: &quot;#$(PageGuid)&quot;,
        ///		store: store,
        ///		data: {
        ///		},
        ///		components: {
        ///			&apos;a2-document-title&apos;: documentTitle
        ///		},
        ///		computed: {
        ///		},
        ///		methods: {
        ///			$close() {
        ///				this.$store.commit(&quot;close&quot;);
        ///			},
        ///			$requery() {
        ///				eventBus.$emit(&apos;r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string appPageScript {
            get {
                return ResourceManager.GetString("appPageScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;modal&quot; id=&quot;$(PageGuid)&quot; v-modal-width=&quot;{cssClass:&apos;modal-small&apos;}&quot;&gt;
        ///	&lt;div class=&quot;modal-header&quot; v-drag-window&gt;
        ///		&lt;span&gt;@[SetNewPassword]&lt;/span&gt;
        ///		&lt;button class=&quot;btnclose&quot; @click.prevent=&quot;$modalClose(false)&quot;&gt;&amp;#x2715;&lt;/button&gt;
        ///	&lt;/div&gt;
        ///	&lt;div class=&quot;load-indicator&quot; v-show=&quot;$isLoading&quot;&gt;&lt;/div&gt;
        ///	&lt;div class=&quot;modal-content&quot;&gt;
        ///		&lt;div class=&quot;grid&quot; style=&quot;grid-template-columns:1fr&quot;&gt;
        ///			&lt;static label=&quot;@[User]&quot; :text=&quot;User.Name&quot; style=&quot;grid-row:1&quot;&gt;&lt;/static&gt;
        ///			&lt;textbox label=&quot;@[OldPassword]&quot; :password=&quot;t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string changePassword {
            get {
                return ResourceManager.GetString("changePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;margin:8px;overflow:auto&quot;&gt;
        ///	&lt;h4 class=&quot;a2-header&quot; v-text=&quot;locale.$ConfirmEMailPrompt&quot;&gt;&lt;/h4&gt;
        ///	&lt;hr style=&quot;margin-top:1rem&quot; /&gt;
        ///	&lt;div&gt;
        ///		&lt;p v-text=&quot;locale.$ConfirmEMailText&quot; style=&quot;margin-bottom:30px&quot;&gt;&lt;/p&gt;
        ///		&lt;a tabindex=&quot;1&quot; href=&quot;/&quot; class=&quot;a2-hyperlink&quot; v-text=&quot;locale.$LoginLink&quot;&gt;&lt;/a&gt;
        ///	&lt;/div&gt;
        ///&lt;/div&gt;
        ///.
        /// </summary>
        internal static string confirmEMail {
            get {
                return ResourceManager.GetString("confirmEMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;div style=&quot;margin:8px;overflow:auto&quot;&gt;
        ///	&lt;h4 class=&quot;a2-header&quot; v-text=&quot;locale.$Error&quot;&gt;&lt;/h4&gt;
        ///	&lt;hr style=&quot;margin-top:1rem&quot; /&gt;
        ///	&lt;div&gt;
        ///		&lt;p v-text=&quot;locale.$ErrorText&quot; style=&quot;margin-bottom:30px&quot;&gt;&lt;/p&gt;
        ///		&lt;p style=&quot;margin-bottom:30px&quot;&gt;$(ErrorMessage)&lt;/p&gt;
        ///		&lt;a tabindex=&quot;3&quot; href=&quot;/account/login&quot; class=&quot;a2-hyperlink&quot; v-text=&quot;locale.$LoginLink&quot;&gt;&lt;/a&gt;
        ///	&lt;/div&gt;
        ///&lt;/div&gt;
        ///.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;modal&quot; id=&quot;$(PageGuid)&quot;&gt;
        ///	&lt;div class=&quot;modal-header&quot; v-drag-window&gt;
        ///		&lt;span&gt;@[Error]&lt;/span&gt;
        ///		&lt;button class=&quot;btnclose&quot; @click.prevent=&quot;$modalClose(false)&quot;&gt;&amp;#x2715;&lt;/button&gt;
        ///	&lt;/div&gt;
        ///	&lt;div class=&quot;modal-body confirm&quot;&gt;
        ///		&lt;i class=&quot;ico ico-confirm&quot;&gt;&lt;/i&gt; 
        ///		&lt;div class=&quot;modal-body-content&quot;&gt;
        ///			&lt;div&gt;$(ErrorMessage)&lt;/div&gt;
        ///		&lt;/div&gt;
        ///	&lt;/div&gt;	
        ///	&lt;div class=&quot;modal-footer&quot;&gt;
        ///		&lt;button class=&quot;btn a2-inline&quot; @click.prevent=&quot;$modalClose()&quot; v-settabindex&gt;@[Close]&lt;/button&gt;
        ///	&lt;/div&gt;
        ///&lt;/div&gt;
        ///
        ///
        ///&lt;script typ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string errorDialog {
            get {
                return ResourceManager.GetString("errorDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;modal&quot; id=&quot;$(PageGuid)&quot; v-modal-width=&quot;{width:&apos;900px&apos;}&quot;&gt;
        ///	&lt;div class=&quot;modal-header&quot; v-drag-window&gt;
        ///		&lt;span&gt;Електронний підпис&lt;/span&gt;
        ///		&lt;button class=&quot;btnclose&quot; @click.prevent=&quot;$modalClose(false)&quot;&gt;&amp;#x2715;&lt;/button&gt;
        ///	&lt;/div&gt;
        ///	&lt;div class=&quot;modal-body&quot;&gt;
        ///		&lt;iframe style=&quot;width:100%;height:700px;border:none&quot; frameborder=&quot;0&quot; :src=&quot;frameUrl&quot;&gt;&lt;/iframe&gt;
        ///	&lt;/div&gt;
        ///	&lt;div class=&quot;modal-footer&quot;&gt;
        ///		&lt;button class=&quot;btn a2-inline&quot; @click.prevent=&quot;$modalClose()&quot; v-settabindex&gt;@[Close]&lt;/button&gt;
        ///	&lt;/div&gt;
        ///&lt;/div&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string euSignDialog {
            get {
                return ResourceManager.GetString("euSignDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;$(Locale)&quot; style=&quot;height:100%&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///	&lt;meta name=&quot;description&quot; content=&quot;$(Description)&quot; /&gt;
        ///	&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///	&lt;meta name=&quot;format-detection&quot; content=&quot;telephone=no&quot; /&gt;
        ///	&lt;link href=&quot;/css/$(Theme).min.css?v=$(Build)&quot; rel=&quot;stylesheet&quot; /&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;script type=&quot;text/javascript&quot; src=&quot;/scripts/vue.js?v=2.5.13&quot;&gt;&lt;/script&gt;
        ///	&lt;script typ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string euSignFrame {
            get {
                return ResourceManager.GetString("euSignFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright © 2015-2018 Alex Kukhtin. All rights reserved.
        ///
        ///&quot;use strict&quot;;
        ///
        ///// global scope!
        ///
        ///const eventBus = require(&apos;std:eventBus&apos;);
        ///
        ///function EUSignCPModuleInitialized(isInitialized) {
        ///	console.info(&apos;EUSign library initialized&apos;);
        ///	var URL_XML_HTTP_PROXY_SERVICE = &quot;/Handlers/ProxyHandler.ashx&quot;;
        ///
        ///	if (isInitialized) {
        ///		euSign.Initialize();
        ///		euSign.SetJavaStringCompliant(true);
        ///		euSign.SetCharset(&quot;UTF-16LE&quot;);
        ///		euSign.SetXMLHTTPProxyService(URL_XML_HTTP_PROXY_SERVICE);
        ///
        ///		var settings = euSig [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string euSignFrameScript {
            get {
                return ResourceManager.GetString("euSignFrameScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;div style=&quot;margin:8px;overflow:auto&quot;&gt;
        ///	&lt;h4 class=&quot;a2-header&quot; v-text=&quot;locale.$ForgotPrompt&quot;&gt;&lt;/h4&gt;
        ///	&lt;hr style=&quot;margin-top:1rem&quot; /&gt;
        ///	&lt;div v-if=&quot;serverError&quot; class=&quot;validation-summary&quot; style=&quot;width:390px;margin-top:10px&quot;&gt;
        ///		&lt;span class=&quot;error&quot; v-text=&quot;serverError&quot;&gt;&lt;/span&gt;
        ///	&lt;/div&gt;
        ///	&lt;div v-if=&quot;showConfirm&quot;&gt;
        ///		&lt;p v-text=&quot;confirmText&quot;&gt;&lt;/p&gt;
        ///		&lt;p v-text=&quot;locale.$CheckEMail&quot;&gt;&lt;/p&gt;
        ///		&lt;a tabindex=&quot;3&quot; :href=&quot;getReferUrl(&apos;/&apos;)&quot; class=&quot;a2-hyperlink&quot; v-text=&quot;locale.$LoginLink&quot;&gt;&lt;/a&gt;
        ///	&lt;/div&gt;
        ///	&lt;div v-else class=&quot;gr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string forgotPassword {
            get {
                return ResourceManager.GetString("forgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright © 2015-2019 Alex Kukhtin. All rights reserved.
        ///// version 7372
        ///
        ///&apos;use strict&apos;;
        ///
        ///(function () {
        ///
        ///
        ///	const token = &apos;$(Token)&apos;;
        ///
        ///
        ///	$(Utils)
        ///	$(Locale)
        ///
        ///	const vm = new Vue({
        ///		el: &quot;#app&quot;,
        ///		data: {
        ///			email: &apos;&apos;,
        ///			processing: false,
        ///			info: $(PageData),
        ///			appLinks: $(AppLinks),
        ///			submitted: false,
        ///			serverError: &apos;&apos;,
        ///			emailError: &apos;&apos;,
        ///			showConfirm: false,
        ///			confirmText: &apos;&apos;
        ///		},
        ///		computed: {
        ///			valid:function() {
        ///				if (!this.submitted) return true;
        ///				return  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string forgotPasswordScript {
            get {
                return ResourceManager.GetString("forgotPasswordScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;$(Lang)&quot;&gt;
        ///&lt;head&gt;
        ///	@(SiteMeta)
        ///	&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///	&lt;meta name=&quot;description&quot; content=&quot;$(Description)&quot; /&gt;
        ///	&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///	&lt;meta name=&quot;format-detection&quot; content=&quot;telephone=no&quot; /&gt;
        ///	&lt;meta name=&quot;google&quot; content=&quot;notranslate&quot; /&gt;
        ///	&lt;meta name=&quot;helpUrl&quot; content=&quot;$(HelpUrl)&quot; /&gt;
        ///	&lt;title&gt;$(Title)&lt;/title&gt;
        ///	&lt;link href=&quot;/css/site.min.css?v=$(Build)&quot; rel=&quot;stylesheet&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string initLayout {
            get {
                return ResourceManager.GetString("initLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;$(Locale)&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///	&lt;meta name=&quot;description&quot; content=&quot;$(Description)&quot; /&gt;
        ///	&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///	&lt;meta name=&quot;format-detection&quot; content=&quot;telephone=no&quot; /&gt;
        ///	&lt;meta name=&quot;google&quot; content=&quot;notranslate&quot; /&gt;
        ///	&lt;meta name=&quot;rootUrl&quot; content=&quot;$(RootUrl)&quot; /&gt;
        ///	&lt;meta name=&quot;helpUrl&quot; content=&quot;$(HelpUrl)&quot; /&gt;
        ///	&lt;meta name=&quot;theme-color&quot; content=&quot;#4d6082&quot; /&gt;
        ///	&lt;ti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string layout {
            get {
                return ResourceManager.GetString("layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;$(Locale)&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///	&lt;meta name=&quot;description&quot; content=&quot;A2:Web&quot; /&gt;
        ///	&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///	&lt;meta name=&quot;format-detection&quot; content=&quot;telephone=no&quot; /&gt;
        ///	&lt;meta name=&quot;rootUrl&quot; content=&quot;$(RootUrl)&quot; /&gt;
        ///	&lt;meta name=&quot;google&quot; content=&quot;notranslate&quot; /&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///	&lt;link href=&quot;/css/site.min.css?v=$(Build)&quot; rel=&quot;stylesheet&quot; /&gt;
        ///	&lt;link rel=&quot;shortcut ic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string layoutAdmin {
            get {
                return ResourceManager.GetString("layoutAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;$(Locale)&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///	&lt;meta name=&quot;description&quot; content=&quot;$(Description)&quot; /&gt;
        ///	&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///	&lt;meta name=&quot;format-detection&quot; content=&quot;telephone=no&quot; /&gt;
        ///	&lt;meta name=&quot;google&quot; content=&quot;notranslate&quot; /&gt;
        ///	&lt;meta name=&quot;rootUrl&quot; content=&quot;$(RootUrl)&quot; /&gt;
        ///	&lt;meta name=&quot;helpUrl&quot; content=&quot;$(HelpUrl)&quot; /&gt;
        ///	&lt;meta name=&quot;theme-color&quot; content=&quot;#4d6082&quot; /&gt;
        ///	&lt;ti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string layoutMobile {
            get {
                return ResourceManager.GetString("layoutMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright © 2015-2019 Alex Kukhtin. All rights reserved.
        ///
        ///// 20190223-7441
        ///// locale-de.js
        ///
        ///&quot;use strict&quot;;
        ///
        ///(function () {
        ///
        ///	window.$$locale = {
        ///		$Locale: &apos;de-DE&apos;,
        ///		$Ok: &apos;OK&apos;,
        ///		$Cancel: &apos;Abbrechen&apos;,
        ///		$Close: &apos;Schließen&apos;,
        ///		$Apply: &apos;Übernehmen&apos;,
        ///		$Back: &apos;Zurück&apos;,
        ///		$Next: &apos;Weiter&apos;,
        ///		$Finish: &apos;Stop&apos;,
        ///		$Tasks: &apos;Aufgaben&apos;,
        ///		$Save: &apos;Speichern&apos;,
        ///		$NotSave: &apos;Nicht speichern&apos;,
        ///		$Refresh: &apos;Aktualisieren&apos;,
        ///		$Confirm: &apos;Bestätigung&apos;,
        ///		$Message: &apos;Nachricht&apos;,
        ///		$Error: &apos;Fehler&apos;,
        ///		$ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string locale_de {
            get {
                return ResourceManager.GetString("locale_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright © 2015-2018 Alex Kukhtin. All rights reserved.
        ///
        ///// 20180401-7145
        ///// locale-en.js
        ///
        ///&quot;use strict&quot;;
        ///
        ///(function () {
        ///
        ///
        ///	const locale = {
        ///		$Locale: &apos;en-US&apos;,
        ///		$Ok: &apos;OK&apos;,
        ///		$Cancel: &apos;Cancel&apos;,
        ///		$Error: &apos;Error&apos;,
        ///		$Login: &apos;Log in&apos;,
        ///		$User: &apos;User&apos;,
        ///		$Confirm: &apos;Confirm&apos;,
        ///		$LoginPrompt: &apos;Login to system&apos;,
        ///		$LoginLink: &apos;Link to login&apos;,
        ///		$RegisterPrompt: &apos;Register in the system.&apos;,
        ///		$ForgotPrompt: &apos;Reset password&apos;,
        ///		$ConfirmEMailPrompt: &apos;Confirm е-mail&apos;,
        ///		$Version: &apos;Version&apos;,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string locale_en {
            get {
                return ResourceManager.GetString("locale_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright © 2015-2018 Alex Kukhtin. All rights reserved.
        ///
        ///// 20180401-7145
        ///// locale-ru.js
        ///
        ///&quot;use strict&quot;;
        ///
        ///(function () {
        ///
        ///
        ///	const locale = {
        ///		$Locale: &apos;ru-RU&apos;,
        ///		$Ok: &apos;OK&apos;,
        ///		$Cancel: &apos;Отмена&apos;,
        ///		$Error: &apos;Ошибка&apos;,
        ///		$Login: &apos;Войти&apos;,
        ///		$User: &apos;Пользователь&apos;,
        ///		$Confirm: &apos;Подтверждение&apos;,
        ///		$LoginPrompt: &apos;Вход в систему&apos;,
        ///		$LoginLink: &apos;На страницу входа&apos;,
        ///		$RegisterPrompt: &apos;Регистрация в системе&apos;,
        ///		$ForgotPrompt: &apos;Восстановление пароля&apos;,
        ///		$ConfirmEMailPrompt: &apos;Подтверждение е-mai [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string locale_ru {
            get {
                return ResourceManager.GetString("locale_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright © 2015-2018 Alex Kukhtin. All rights reserved.
        ///
        ///// 20180401-7145
        ///// locale-uk.js
        ///
        ///&quot;use strict&quot;;
        ///
        ///(function () {
        ///
        ///
        ///	const locale = {
        ///		$Locale: &apos;uk-UA&apos;,
        ///		$Ok: &apos;OK&apos;,
        ///		$Cancel: &apos;Скасувати&apos;,
        ///		$Error: &apos;Помилка&apos;,
        ///		$Login: &apos;Увійти&apos;,
        ///		$User: &apos;Користувач&apos;,
        ///		$Confirm: &apos;Підтвердження&apos;,
        ///		$LoginPrompt: &apos;Вхід в систему&apos;,
        ///		$LoginLink: &apos;До сторінки входу&apos;,
        ///		$RegisterPrompt: &apos;Реєстрація в системі&apos;,
        ///		$ForgotPrompt: &apos;Відновлення паролю&apos;,
        ///		$ConfirmEMailPrompt: &apos;Підтвердження е-mail [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string locale_uk {
            get {
                return ResourceManager.GetString("locale_uk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;margin:8px;overflow:auto&quot;&gt;
        ///	&lt;h4 class=&quot;a2-header&quot; v-text=&quot;locale.$LoginPrompt&quot;&gt;&lt;/h4&gt;
        ///	&lt;hr style=&quot;margin-top:1rem&quot; /&gt;
        ///	&lt;div v-if=&quot;serverError&quot; class=&quot;validation-summary&quot; style=&quot;width:390px;margin-top:10px&quot;&gt;
        ///		&lt;span class=&quot;error&quot; v-text=&quot;serverError&quot;&gt;&lt;/span&gt;
        ///	&lt;/div&gt;
        ///	&lt;form&gt;
        ///		&lt;div class=&quot;grid&quot; style=&quot;grid-template-columns:auto 1fr; width:400px&quot;&gt;
        ///			&lt;label style=&quot;grid-row:1; grid-column:1&quot; class=&quot;a2-label required text-right&quot; v-text=&quot;locale.$Email&quot;&gt;&lt;/label&gt;
        ///			&lt;div class=&quot;control-group&quot; st [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright © 2015-2019 Alex Kukhtin. All rights reserved.
        ///
        ///&quot;use strict&quot;;
        ///
        ///(function () {
        ///
        ///
        ///	const token = &apos;$(Token)&apos;;
        ///
        ///	$(Utils)
        ///	$(Locale)
        ///
        ///	const vm = new Vue({
        ///		el: &quot;#app&quot;,
        ///		data: {
        ///			email: &apos;&apos;,
        ///			password: &apos;&apos;,
        ///			rememberMe: false,
        ///			processing: false,
        ///			info: $(PageData),
        ///			appLinks: $(AppLinks),
        ///			submitted: false,
        ///			serverError: &apos;&apos;,
        ///			emailError: &apos;&apos;
        ///		},
        ///		computed: {
        ///			valid: function() {
        ///				if (!this.submitted) return true;
        ///				return this.validEmail &amp;&amp; thi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string loginScript {
            get {
                return ResourceManager.GetString("loginScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright © 2015-2018 Alex Kukhtin. All rights reserved.
        ///
        ////*20180821-7279*/
        ////* services/mask.js */
        ///
        ///function maskTool() {
        ///
        ///
        ///	const PLACE_CHAR = &apos;_&apos;;
        ///
        ///	return {
        ///		getMasked: getMasked,
        ///		getUnmasked: getUnmasked,
        ///		mountElement: mountElement,
        ///		unmountElement: unmountElement,
        ///		setMask: setMask
        ///	};
        ///
        ///	function isMaskChar(ch) {
        ///		return ch === &apos;#&apos; || ch === &apos;@&apos;;
        ///	}
        ///
        ///	function isSpaceChar(ch) {
        ///		return &apos;- ()&apos;.indexOf(ch) !== -1;
        ///	}
        ///
        ///	function isValidChar(mask, char) {
        ///		if (mask = [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mask {
            get {
                return ResourceManager.GetString("mask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright © 2015-2018 Alex Kukhtin. All rights reserved.
        ///
        ///Vue.directive(&apos;focus&apos;, {
        ///	bind: function(el, binding, vnode) {
        ///
        ///		el.addEventListener(&quot;focus&quot;, function (event) {
        ///			event.target.parentElement.classList.add(&apos;focus&apos;);
        ///		}, false);
        ///
        ///		el.addEventListener(&quot;blur&quot;, function (event) {
        ///			let t = event.target;
        ///			t._selectDone = false;
        ///			event.target.parentElement.classList.remove(&apos;focus&apos;);
        ///		}, false);
        ///
        ///		el.addEventListener(&quot;click&quot;, function (event) {
        ///			let t = event.target;
        ///			if  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pageUtils {
            get {
                return ResourceManager.GetString("pageUtils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;margin:8px;overflow:auto&quot;&gt;
        ///	&lt;h4 class=&quot;a2-header&quot; v-text=&quot;locale.$RegisterPrompt&quot;&gt;&lt;/h4&gt;
        ///	&lt;hr style=&quot;margin-top:1rem&quot; /&gt;
        ///	&lt;div v-if=&quot;serverError&quot; class=&quot;validation-summary&quot; style=&quot;width:390px;margin-top:10px&quot;&gt;
        ///		&lt;span class=&quot;error&quot; v-text=&quot;serverError&quot;&gt;&lt;/span&gt;
        ///	&lt;/div&gt;
        ///	&lt;form&gt;
        ///		&lt;div v-if=&quot;showConfirm&quot; class=&quot;user-select&quot;&gt;
        ///			&lt;p v-text=&quot;confirmRegisterText&quot;&gt;&lt;/p&gt;
        ///			&lt;p v-text=&quot;locale.$CheckEMail&quot;&gt;&lt;/p&gt;
        ///			&lt;a tabindex=&quot;3&quot; href=&quot;/&quot; class=&quot;a2-hyperlink&quot; v-text=&quot;locale.$LoginLink&quot;&gt;&lt;/a&gt;
        ///		&lt;/di [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string registerTenant {
            get {
                return ResourceManager.GetString("registerTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright © 2015-2019 Alex Kukhtin. All rights reserved.
        ///
        ///&quot;use strict&quot;;
        ///
        ///(function () {
        ///
        ///
        ///	const token = &apos;$(Token)&apos;;
        ///
        ///	$(Utils)
        ///	$(Locale)
        ///	$(Mask)
        ///
        ///	const maskTools = maskTool();
        ///
        ///	// TODO: from LOCALE or WEB.CONFIG
        ///	const currentMask = &apos;+38 (0##) ###-##-##&apos;;
        ///
        ///	const vm = new Vue({
        ///		el: &quot;#app&quot;,
        ///		data: {
        ///			email: &apos;&apos;,
        ///			name: &apos;&apos;,
        ///			phone: &apos;&apos;,
        ///			password: &apos;&apos;,
        ///			confirm: &apos;&apos;,
        ///			processing: false,
        ///			info: $(PageData),
        ///			appLinks: $(AppLinks),
        ///			submitted: false,
        ///			ser [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string registerTenantScript {
            get {
                return ResourceManager.GetString("registerTenantScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;margin:8px;overflow:auto&quot;&gt;
        ///	&lt;h4 class=&quot;a2-header&quot; v-text=&quot;locale.$ResetPasswordTitle&quot;&gt;&lt;/h4&gt;
        ///	&lt;hr style=&quot;margin-top:1rem&quot; /&gt;
        ///	&lt;div v-if=&quot;serverError&quot; class=&quot;validation-summary&quot; style=&quot;width:390px;margin-top:10px&quot;&gt;
        ///		&lt;span class=&quot;error&quot; v-text=&quot;serverError&quot;&gt;&lt;/span&gt;
        ///	&lt;/div&gt;
        ///	&lt;form&gt;
        ///		&lt;div v-if=&quot;showConfirm&quot;&gt;
        ///			&lt;p v-text=&quot;locale.$ResetPasswordSuccess&quot;&gt;
        ///			&lt;/p&gt;
        ///			&lt;a tabindex=&quot;1&quot; href=&quot;/&quot; class=&quot;a2-hyperlink&quot; v-text=&quot;locale.$LoginLink&quot;&gt;&lt;/a&gt;
        ///		&lt;/div&gt;
        ///		&lt;div v-else class=&quot;grid&quot; style=&quot;grid [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string resetPassword {
            get {
                return ResourceManager.GetString("resetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright © 2015-2017 Alex Kukhtin. All rights reserved.
        ///// version 7372
        ///
        ///(function () {
        ///
        ///
        ///	const token = &apos;$(Token)&apos;;
        ///
        ///	$(Utils)
        ///	$(Locale)
        ///
        ///	const vm = new Vue({
        ///		el: &quot;#app&quot;,
        ///		data: {
        ///			email: &apos;&apos;,
        ///			password: &apos;&apos;,
        ///			confirm: &apos;&apos;,
        ///			processing: false,
        ///			info: $(PageData),
        ///			appLinks: $(AppLinks),
        ///			serverInfo: $(ServerInfo),
        ///			submitted: false,
        ///			serverError: &apos;&apos;,
        ///			emailError: &apos;&apos;,
        ///			showConfirm: false,
        ///			passwordError: &apos;&apos;
        ///		},
        ///		computed: {
        ///			locale() {
        ///				retur [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string resetPasswordScript {
            get {
                return ResourceManager.GetString("resetPasswordScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////*20181005-7312*/
        ///
        ///(function () {
        ///
        ///	const Shell = component(&apos;std:shellController&apos;);
        ///
        ///	const menu = $(Menu);
        ///
        ///	const shell = new Shell({
        ///		el: &apos;#shell&apos;,
        ///		data: {
        ///			version: &apos;$(AppVersion)&apos;,
        ///			menu: menu.Menu ? menu.Menu[0].Menu : null,
        ///			newMenu: menu.NewMenu,
        ///			settingsMenu: menu.SettingsMenu,
        ///			title: menu.SysParams ? menu.SysParams.AppTitle : &apos;&apos;,
        ///			subtitle: menu.SysParams ? menu.SysParams.AppSubTitle : &apos;&apos;,
        ///			sideBarMode: menu.SysParams ? menu.SysParams.SideBarMode : &apos;&apos;,
        ///			use [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string shell {
            get {
                return ResourceManager.GetString("shell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright © 2015-2018 Alex Kukhtin. All rights reserved.
        ///
        ////*20181005-7312*/
        ///
        ///(function () {
        ///
        ///	const Shell = component(&apos;std:shellController&apos;);
        ///
        ///	const menu = $(Menu);
        ///
        ///	const shell = new Shell({
        ///		el: &apos;#shell&apos;,
        ///		data: {
        ///			title: menu.SysParams ? menu.SysParams.AppTitle : &apos;&apos;,
        ///			subtitle: &apos;администратор&apos;,
        ///			version: &apos;$(AppVersion)&apos;,
        ///			menu: menu.Menu[0].Menu
        ///		}
        ///	});
        ///
        ///	window.$$rootUrl = &apos;/admin&apos;;
        ///	window.$$debug = $(Debug);
        ///
        ///})();.
        /// </summary>
        internal static string shellAdmin {
            get {
                return ResourceManager.GetString("shellAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright © 2015-2018 Alex Kukhtin. All rights reserved.
        ///
        ///(function () {
        ///
        ///	$(Utils)
        ///	$(Locale)
        ///
        ///	const vm = new Vue({
        ///		el: &quot;#app&quot;,
        ///		data: {
        ///			info: $(PageData),
        ///			appLinks: $(AppLinks),
        ///			processing: false
        ///		},
        ///		computed: {
        ///			locale() {
        ///				return window.$$locale;
        ///			}
        ///		},
        ///		methods: {
        ///			getReferUrl(url) {
        ///				return getReferralUrl(url);
        ///			}
        ///		}
        ///	});
        ///})();.
        /// </summary>
        internal static string simpleScript {
            get {
                return ResourceManager.GetString("simpleScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright © 2015-2018 Alex Kukhtin. All rights reserved.
        ///
        ///(function () {
        ///
        ///
        ///	let cm = window.$currentModule();
        ///
        ///	const DialogController = component(&apos;standaloneController&apos;);
        ///
        ///	const vm = new DialogController({
        ///		el: &quot;#$(PageGuid)&quot;,
        ///		props: {
        ///			inDialog: { type: Boolean, default: true }
        ///		},
        ///		data: cm.dataModel
        ///	});
        ///
        ///	DialogController.init(vm, null);
        ///
        ///})();.
        /// </summary>
        internal static string standaloneDialogScript {
            get {
                return ResourceManager.GetString("standaloneDialogScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;$(Lang)&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///	&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot; /&gt;
        ///	&lt;meta name=&quot;google&quot; content=&quot;notranslate&quot; /&gt;
        ///	&lt;title&gt;$(Title)&lt;/title&gt;
        ///	&lt;link rel=&quot;shortcut icon&quot; href=&quot;/favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///	&lt;link rel=&quot;icon&quot; href=&quot;/favicon.ico&quot; type=&quot;image/x-icon&quot; /&gt;
        ///	&lt;style&gt;
        ///		body {
        ///			background-color: #e3e3e3;
        ///			width:100%;
        ///			height:100%;
        ///			padding:0;
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stiReport {
            get {
                return ResourceManager.GetString("stiReport", resourceCulture);
            }
        }
    }
}
