#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Dynamic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using A2v10.Web.Mvc;
    
    #line 1 "..\..\Views\Account\Login.cshtml"
    using A2v10.Web.Mvc.Models;
    
    #line default
    #line hidden
    using Microsoft.AspNet.Identity;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/Login.cshtml")]
    public partial class _Views_Account_Login_cshtml : System.Web.Mvc.WebViewPage<LoginViewModel>
    {
        public _Views_Account_Login_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Account\Login.cshtml"
  
    ViewBag.Title = "Log in";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>");

            
            #line 7 "..\..\Views\Account\Login.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h2>\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div>\r\n");

            
            #line 10 "..\..\Views\Account\Login.cshtml"
        
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Account\Login.cshtml"
         using (Html.BeginForm("Login", "Account", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Account\Login.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Account\Login.cshtml"
                                    

            
            #line default
            #line hidden
WriteLiteral("            <h4>Use a local account to log in.</h4>\r\n");

WriteLiteral("            <hr />\r\n");

            
            #line 15 "..\..\Views\Account\Login.cshtml"
            
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Account\Login.cshtml"
       Write(Html.ValidationSummary(true, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Account\Login.cshtml"
                                                                             

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"grid\"");

WriteLiteral(" style=\"grid-template-columns:auto 1fr;width:400px\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" style=\"grid-row:1; grid-column:1\"");

WriteLiteral(" class=\"required\"");

WriteLiteral(">Логин</label>\r\n                <div");

WriteLiteral(" class=\"control-group\"");

WriteLiteral(" style=\"grid-row:1;grid-column:2\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 20 "..\..\Views\Account\Login.cshtml"
                   Write(Html.TextBoxFor(m => m.Name, new { @class = "control", style = "grid-row:1; grid-column:2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n");

WriteLiteral("                    ");

            
            #line 22 "..\..\Views\Account\Login.cshtml"
               Write(Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <label");

WriteLiteral(" style=\"grid-row:2; grid-column:1\"");

WriteLiteral(" class=\"required\"");

WriteLiteral(">Пароль</label>\r\n                <div");

WriteLiteral(" class=\"control-group\"");

WriteLiteral(" style=\"grid-row:2;grid-column:2\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 27 "..\..\Views\Account\Login.cshtml"
                   Write(Html.PasswordFor(m => m.Password, new { @class = "control", style = "grid-row:2;grid-column:2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n");

WriteLiteral("                    ");

            
            #line 29 "..\..\Views\Account\Login.cshtml"
               Write(Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <label");

WriteLiteral(" class=\"checkbox\"");

WriteLiteral(" style=\"grid-row:3;grid-column:2\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"RememberMe\"");

WriteLiteral(" value=\"true\"");

WriteLiteral("/>\r\n                    <span>Запомнить учетные данные</span>\r\n                </" +
"label>\r\n                <input");

WriteLiteral(" name=\"RememberMe\"");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" value=\"false\"");

WriteLiteral("/>\r\n");

WriteLiteral("                ");

            
            #line 36 "..\..\Views\Account\Login.cshtml"
           Write(Html.CheckBoxFor(m => m.RememberMe));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <div");

WriteLiteral(" style=\"grid-row:4;grid-column:2\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(">Вход в систему</button>\r\n                </div>\r\n            </div>\r\n");

WriteLiteral("            <p>\r\n");

WriteLiteral("                ");

            
            #line 42 "..\..\Views\Account\Login.cshtml"
           Write(Html.ActionLink("Register as a new user", "Register"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </p>\r\n");

            
            #line 44 "..\..\Views\Account\Login.cshtml"
            
            
            #line default
            #line hidden
            
            #line 47 "..\..\Views\Account\Login.cshtml"
                      
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
