//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by A2v10.Designer.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_POPUP_EDIT                  119
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_JSMODULE					129
#define IDR_A2v10DesignerTYPE           131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define IDS_FILE_VIEW                   155
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_OUTPUT_WND_HC               166
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDR_OUTPUT_POPUP                182
#define ID_EXPAND_ALL                   201
#define ID_PROPERTIES1                  203
#define ID_PROPERTIES2                  204
#define IDS_OUTPUT_WND                  206
#define IDR_MENU_IMAGES                 230
#define IDR_TOOLBOX                     232
#define IDR_PROPERTIES                  234
#define IDR_PRINTPREVIEW                236
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define ID_VIEW_OUTPUTWND               400
#define ID_WND_PROPERTIES               500
#define ID_WND_TOOLBOX                  501
#define ID_WND_COMMAND                  502
#define ID_WND_SOLUTION                 503
#define ID_WND_OUTLINE                  504
#define IDM_POPUP_MENU                  600
#define IDD_OPTION_GENERAL              800
#define IDS_OPTIONS_CAPTION             12000
#define IDS_LANGUAGES                   12001
#define IDC_DIALOG_FIRST                14000
#define IDC_COMBO1                      14001
#define IDC_COMBO2                      14002
#define IDC_COMBO3                      14003
#define IDC_COMBO4                      14004
#define IDC_COMBO5                      14005
#define IDC_TITLE1                      14006
#define IDC_TITLE2                      14007
#define IDC_TITLE3                      14008
#define IDC_TITLE4                      14009
#define IDC_TITLE5                      14010
#define IDC_PROMPT1                     14011
#define IDC_PROMPT2                     14012
#define IDC_PROMPT3                     14013
#define IDC_PROMPT4                     14014
#define IDC_PROMPT5                     14015
#define ID_FILE_OPEN_SOLUTION           32000
#define ID_FILE_CLOSE_SOLUTION          32001
#define ID_FILE_SAVE_ALL                32002
#define ID_EDIT_FIND_IN_FILES           32100
#define ID_VIEW_PROPERTIES              32200
#define ID_VIEW_TOOLBOX                 32201
#define ID_VIEW_COMMAND                 32202
#define ID_VIEW_SOLUTION                32203
#define ID_VIEW_OUTLINE                 32204
#define ID_DEBUG_RUN                    32300
#define ID_DEBUG_RUN_INT                32301
#define ID_TOOLS_OPTIONS                32400
#define ID_TOOLBOX_FIRST				32500
#define ID_TOOLBOX_POINTER				32500
#define ID_TOOLBOX_LABEL				32501
#define ID_TOOLBOX_EDITOR				32502
#define ID_TOOLBOX_BUTTON				32503
#define ID_TOOLBOX_CHECK				32504
#define ID_TOOLBOX_RADIO				32505
#define ID_TOOLBOX_COMBOBOX				32506
#define ID_TOOLBOX_DATAGRID				32507
#define ID_TOOLBOX_DATEPICKER			32508
#define ID_TOOLBOX_CANVAS				32509
#define ID_TOOLBOX_GRID					32510
#define ID_TOOLBOX_DOCKPANEL			32511
#define ID_TOOLBOX_STACKPANEL			32512
#define ID_TOOLBOX_LAST					32512
#define ID_WINDOW_MANAGER               32600
#define ID_WINDOW_CLOSE_ALL             32601
#define ID_PROP_ALPHABETICAL            32700
#define ID_PROP_CATEGORIZED             32701
#define IDP_OLE_INIT_FAILED             51000
#define IDP_RICH_INIT_FAILED            51001
#define IDP_SCI_INIT_FAILED             51002
#define IDMENU_CLOSE                    0xD000
#define IDMENU_RESTORE                  0xD001
#define IDMENU_MAXIMIZE                 0xD002
#define IDMENU_MINIMIZE                 0xD003
#define IDMENU_HELP                     0xD004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        311
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
